#!/usr/bin/env node

/**
 * Generate src/project/generatedLoader.ts for a given demo.
 *
 * The file is gitignored and machine-written; it exists only so the dev
 * server (src/main.ts) has literal glob paths for the chosen demo.
 *
 * - `node scripts/generate-loader.cjs`         → write default demo ONLY if missing
 *   (used as predev/prebuild hook so fresh clones typecheck and build)
 * - `require(...).writeLoader('examples/foo')` → always write (used by dev-demo.cjs)
 */

const fs = require('fs');
const path = require('path');

const DEFAULT_DEMO = 'examples/hello-shader';
const LOADER_PATH = path.resolve(__dirname, '..', 'src/project/generatedLoader.ts');

function writeLoader(demo) {
  const loaderContent = `// Auto-generated by scripts/generate-loader.cjs - DO NOT EDIT
import { loadDemo } from './loaderHelper';
import { ProjectConfig } from './types';

export const DEMO_NAME = 'demos/${demo}';

// Transform glob keys from "/path" to "./path" format
function transformKeys<T>(files: Record<string, T>): Record<string, T> {
  const result: Record<string, T> = {};
  for (const [key, value] of Object.entries(files)) {
    // Convert /demos/... to ./demos/...
    const newKey = key.startsWith('/') ? '.' + key : key;
    result[newKey] = value;
  }
  return result;
}

export async function loadDemoProject() {
  // Use root-relative paths for globs (works from any file location)
  const glslFilesRaw = import.meta.glob<string>('/demos/${demo}/**/*.glsl', {
    query: '?raw',
    import: 'default',
  });

  const jsonFilesRaw = import.meta.glob<ProjectConfig>('/demos/${demo}/**/*.json', {
    import: 'default',
  });

  const imageFilesRaw = import.meta.glob<string>('/demos/${demo}/**/*.{jpg,jpeg,png,gif,webp,bmp}', {
    query: '?url',
    import: 'default',
  });

  // Script files (setup.js / script.js hooks for JS-driven computation)
  const scriptFilesRaw = import.meta.glob<any>('/demos/${demo}/**/script.js');

  // Raw script text (retained for HTML export's embedded module)
  const rawScriptRaw = import.meta.glob<string>('/demos/${demo}/**/script.js', {
    query: '?raw',
    import: 'default',
  });

  // Transform keys to ./ format that loadDemo expects
  const glslFiles = transformKeys(glslFilesRaw);
  const jsonFiles = transformKeys(jsonFilesRaw);
  const imageFiles = transformKeys(imageFilesRaw);
  const scriptFiles = transformKeys(scriptFilesRaw);
  const rawScriptFiles = transformKeys(rawScriptRaw);

  return loadDemo(DEMO_NAME, glslFiles, jsonFiles, imageFiles, scriptFiles, rawScriptFiles);
}
`;
  fs.writeFileSync(LOADER_PATH, loaderContent);
}

function ensureLoader() {
  if (!fs.existsSync(LOADER_PATH)) {
    console.log(`Generating default demo loader (${DEFAULT_DEMO})...`);
    writeLoader(DEFAULT_DEMO);
  }
}

module.exports = { writeLoader, ensureLoader, DEFAULT_DEMO };

if (require.main === module) {
  ensureLoader();
}
